### ISSUE TITLE
"warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated"

### ISSUE THREAD

**Issue by 0xCMP** [mutecomm/go-sqlcipher#5]
Installing github.com/gobuffalo/buffalo/buffalo and I got this warning.

```
# github.com/mutecomm/go-sqlcipher
../../go/src/github.com/mutecomm/go-sqlcipher/sqlite3.c:20897:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here
```

**Comment by joeblew99** [comment]
me too !


x-MacBook-Pro:bench apple$ go get github.com/mutecomm/go-sqlcipher
# github.com/mutecomm/go-sqlcipher
../../../mutecomm/go-sqlcipher/sqlite3.c:20897:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by joeblew99** [comment]
however when i use the simple example it works fine.

**Comment by frankbraun** [comment]
I just pushed  commit 7fafec4 which should fix the issue. Could you please test it on macOS 10.12 and close the issue if it works? I'm currently on Linux.

**Comment by joeblew99** [comment]
@frankbraun 

seems its still broken. i cleaned the pkg and src folders also to be sure.

````

x-MacBook-Pro:simple apple$ go get github.com/mutecomm/go-sqlcipher
x-MacBook-Pro:simple apple$ go get -u -v github.com/mutecomm/go-sqlcipher
github.com/mutecomm/go-sqlcipher (download)
github.com/mutecomm/go-sqlcipher
# github.com/mutecomm/go-sqlcipher
../../sqlite3.c:24328:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

````

**Comment by frankbraun** [comment]
I applied the fix from upstream for the same problem (mattn/go-sqlite3#311). That should finally fix it. Please test and close issue.

**Comment by joeblew99** [comment]
@frankbraun 

all good for me on OSX go 1.8.1

@0xCMP good for you ??

````
x-MacBook-Pro:simple apple$ go run simple.go 
0 こんにちわ世界000
1 こんにちわ世界001
2 こんにちわ世界002
3 こんにちわ世界003
4 こんにちわ世界004
5 こんにちわ世界005
6 こんにちわ世界006
7 こんにちわ世界007
8 こんにちわ世界008
9 こんにちわ世界009
...
````

**Comment by frankbraun** [comment]
I consider this closed, please reopen if the problem persists.
